#pragma once

#include <stdint.h>

namespace wv {

enum Scancode : uint32_t
{
	SCANCODE_NONE = 0,
	
	// Alphabetical Keys
	SCANCODE_A = 4,
	SCANCODE_B,
	SCANCODE_C,
	SCANCODE_D,
	SCANCODE_E,
	SCANCODE_F,
	SCANCODE_G,
	SCANCODE_H,
	SCANCODE_I,
	SCANCODE_J,
	SCANCODE_K,
	SCANCODE_L,
	SCANCODE_M,
	SCANCODE_N,
	SCANCODE_O,
	SCANCODE_P,
	SCANCODE_Q,
	SCANCODE_R,
	SCANCODE_S,
	SCANCODE_T,
	SCANCODE_U,
	SCANCODE_V,
	SCANCODE_W,
	SCANCODE_X,
	SCANCODE_Y,
	SCANCODE_Z,

	// Alphanumerical Keys (1,2,3,4,5,6,7,8,9,0)
	SCANCODE_ALPHA_1 = 30,
	SCANCODE_ALPHA_2, 
	SCANCODE_ALPHA_3, 
	SCANCODE_ALPHA_4, 
	SCANCODE_ALPHA_5, 
	SCANCODE_ALPHA_6, 
	SCANCODE_ALPHA_7, 
	SCANCODE_ALPHA_8, 
	SCANCODE_ALPHA_9, 
	SCANCODE_ALPHA_0,

	SCANCODE_RETURN = 40,
	SCANCODE_ESCAPE,
	SCANCODE_BACKSPACE,
	SCANCODE_TAB,
	SCANCODE_SPACE,
	SCANCODE_MINUS,
	SCANCODE_EQUALS,
	SCANCODE_LEFT_BRACKET,
	SCANCODE_RIGHT_BRACKET,
	SCANCODE_BACKSLASH,
	// 50 is treated as 49, do not use
	SCANCODE_SEMICOLON = 51,
	SCANCODE_APOSTROPHE,
	SCANCODE_GRAVE,
	SCANCODE_COMMA,
	SCANCODE_PERIOD,
	SCANCODE_SLASH,

	SCANCODE_CAPSLOCK = 57,
};

enum ControllerButton : uint32_t
{
	CONTROLLER_BUTTON_NONE = 0,
	CONTROLLER_BUTTON_A = 1 << 0, 
	CONTROLLER_BUTTON_B = 1 << 1, 
	CONTROLLER_BUTTON_X = 1 << 2, 
	CONTROLLER_BUTTON_Y = 1 << 3,
	
	CONTROLLER_BUTTON_DPAD_UP    = 1 << 4,
	CONTROLLER_BUTTON_DPAD_RIGHT = 1 << 5,
	CONTROLLER_BUTTON_DPAD_DOWN  = 1 << 6,
	CONTROLLER_BUTTON_DPAD_LEFT  = 1 << 7,

	CONTROLLER_BUTTON_START  = 1 << 8,
	CONTROLLER_BUTTON_SELECT = 1 << 9,
	CONTROLLER_BUTTON_HOME   = 1 << 10, // Centre Button

	CONTROLLER_BUTTON_JOYSTICK_LEFT  = 1 << 11,
	CONTROLLER_BUTTON_JOYSTICK_RIGHT = 1 << 12,

	CONTROLLER_BUTTON_SHOULDER_LEFT  = 1 << 13,
	CONTROLLER_BUTTON_SHOULDER_RIGHT = 1 << 14,

	CONTROLLER_BUTTON_MAX
};

}